# -*- coding: utf-8 -*-
"""
ReklaminiaiParduotuviųLankstinukai
Copyright (C) <2014> <Algirdas Butkus> <butkus.algirdas@gmail.com>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
version = 0.008
from PyQt4 import QtCore, QtGui, QtWebKit
import os

def SEP(path):
    separator = os.path.sep
    if separator != '/':
        path = path.replace('/', os.path.sep)
    return path
    
userdir = os.path.expanduser('~')
userprogpath = SEP('/.cache/deadprogram/')

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1061, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 600))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans"))
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/image.png"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setMargin(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 27))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.pdftab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdftab.sizePolicy().hasHeightForWidth())
        self.pdftab.setSizePolicy(sizePolicy)
        self.pdftab.setObjectName(_fromUtf8("pdftab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pdftab)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setContentsMargins(-1, 2, -1, 1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBox_2 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.comboBox_2.setFont(font)
        self.comboBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.comboBox_3 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_3)
        self.comboBox_4 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_4.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_4)
        self.comboBox_6 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_6.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_6)
        self.comboBox_5 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_5.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_5)
        self.comboBox_7 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setMinimumSize(QtCore.QSize(130, 0))
        self.comboBox_7.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_7)
        self.comboBox_10 = QtGui.QComboBox(self.pdftab)
        self.comboBox_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.comboBox_10.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_10)
        self.comboBox_11 = QtGui.QComboBox(self.pdftab)
        self.comboBox_11.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_11.setObjectName(_fromUtf8("comboBox_11"))
        self.comboBox_11.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_11)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.checkBox_5 = QtGui.QCheckBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setMaximumSize(QtCore.QSize(16777215, 23))
        self.checkBox_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_5.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/zoom-fit.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.checkBox_5.setIcon(icon1)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 23))
        self.doubleSpinBox.setPrefix(_fromUtf8(""))
        self.doubleSpinBox.setSuffix(_fromUtf8(""))
        self.doubleSpinBox.setDecimals(2)
        self.doubleSpinBox.setMinimum(0.5)
        self.doubleSpinBox.setMaximum(1.5)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        self.pushButton_11 = QtGui.QPushButton(self.pdftab)
        self.pushButton_11.setMaximumSize(QtCore.QSize(27, 23))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-up.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_5.addWidget(self.pushButton_11)
        self.pushButton_6 = QtGui.QPushButton(self.pdftab)
        self.pushButton_6.setMaximumSize(QtCore.QSize(27, 23))
        self.pushButton_6.setBaseSize(QtCore.QSize(0, 27))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-down.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(1)
        self.horizontalLayout_12.setContentsMargins(-1, 1, -1, 2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.comboBox_12 = QtGui.QComboBox(self.pdftab)
        self.comboBox_12.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_12.setObjectName(_fromUtf8("comboBox_12"))
        self.comboBox_12.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_12)
        self.comboBox_13 = QtGui.QComboBox(self.pdftab)
        self.comboBox_13.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_13.setObjectName(_fromUtf8("comboBox_13"))
        self.comboBox_13.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_13)
        self.comboBox_14 = QtGui.QComboBox(self.pdftab)
        self.comboBox_14.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_14.setObjectName(_fromUtf8("comboBox_14"))
        self.comboBox_14.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_14)
        self.comboBox_8 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_8.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_8)
        self.comboBox_9 = QtGui.QComboBox(self.pdftab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_9.setMaximumSize(QtCore.QSize(100, 23))
        self.comboBox_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.comboBox_9)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.line_2 = QtGui.QFrame(self.pdftab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.webView_2 = QtWebKit.QWebView(self.pdftab)
        self.webView_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.webView_2.setAutoFillBackground(False)
        self.webView_2.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView_2.setObjectName(_fromUtf8("webView_2"))
        self.verticalLayout_4.addWidget(self.webView_2)
        self.tabWidget.addTab(self.pdftab, _fromUtf8(""))
        self.Internettab = QtGui.QWidget()
        self.Internettab.setObjectName(_fromUtf8("Internettab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Internettab)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setContentsMargins(0, 2, 0, 1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Intbuttonmaxima = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Intbuttonmaxima.sizePolicy().hasHeightForWidth())
        self.Intbuttonmaxima.setSizePolicy(sizePolicy)
        self.Intbuttonmaxima.setMinimumSize(QtCore.QSize(0, 0))
        self.Intbuttonmaxima.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Intbuttonmaxima.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Intbuttonmaxima.setAcceptDrops(False)
        self.Intbuttonmaxima.setCheckable(True)
        self.Intbuttonmaxima.setChecked(False)
        self.Intbuttonmaxima.setFlat(False)
        self.Intbuttonmaxima.setObjectName(_fromUtf8("Intbuttonmaxima"))
        self.horizontalLayout_2.addWidget(self.Intbuttonmaxima)
        self.Intbuttonnorfa = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Intbuttonnorfa.sizePolicy().hasHeightForWidth())
        self.Intbuttonnorfa.setSizePolicy(sizePolicy)
        self.Intbuttonnorfa.setMinimumSize(QtCore.QSize(0, 0))
        self.Intbuttonnorfa.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Intbuttonnorfa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Intbuttonnorfa.setCheckable(True)
        self.Intbuttonnorfa.setFlat(False)
        self.Intbuttonnorfa.setObjectName(_fromUtf8("Intbuttonnorfa"))
        self.horizontalLayout_2.addWidget(self.Intbuttonnorfa)
        self.Intbuttoniki = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Intbuttoniki.sizePolicy().hasHeightForWidth())
        self.Intbuttoniki.setSizePolicy(sizePolicy)
        self.Intbuttoniki.setMinimumSize(QtCore.QSize(0, 0))
        self.Intbuttoniki.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Intbuttoniki.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Intbuttoniki.setCheckable(True)
        self.Intbuttoniki.setFlat(False)
        self.Intbuttoniki.setObjectName(_fromUtf8("Intbuttoniki"))
        self.horizontalLayout_2.addWidget(self.Intbuttoniki)
        self.Intbuttonrimi = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Intbuttonrimi.sizePolicy().hasHeightForWidth())
        self.Intbuttonrimi.setSizePolicy(sizePolicy)
        self.Intbuttonrimi.setMinimumSize(QtCore.QSize(0, 0))
        self.Intbuttonrimi.setMaximumSize(QtCore.QSize(16777215, 23))
        self.Intbuttonrimi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Intbuttonrimi.setCheckable(True)
        self.Intbuttonrimi.setFlat(False)
        self.Intbuttonrimi.setObjectName(_fromUtf8("Intbuttonrimi"))
        self.horizontalLayout_2.addWidget(self.Intbuttonrimi)
        self.intbuttonaibe = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intbuttonaibe.sizePolicy().hasHeightForWidth())
        self.intbuttonaibe.setSizePolicy(sizePolicy)
        self.intbuttonaibe.setMinimumSize(QtCore.QSize(0, 0))
        self.intbuttonaibe.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonaibe.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonaibe.setCheckable(True)
        self.intbuttonaibe.setObjectName(_fromUtf8("intbuttonaibe"))
        self.horizontalLayout_2.addWidget(self.intbuttonaibe)
        self.intbuttonFRESH_MARKET = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intbuttonFRESH_MARKET.sizePolicy().hasHeightForWidth())
        self.intbuttonFRESH_MARKET.setSizePolicy(sizePolicy)
        self.intbuttonFRESH_MARKET.setMinimumSize(QtCore.QSize(0, 0))
        self.intbuttonFRESH_MARKET.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonFRESH_MARKET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonFRESH_MARKET.setCheckable(True)
        self.intbuttonFRESH_MARKET.setObjectName(_fromUtf8("intbuttonFRESH_MARKET"))
        self.horizontalLayout_2.addWidget(self.intbuttonFRESH_MARKET)
        self.intbuttonPROMO = QtGui.QPushButton(self.Internettab)
        self.intbuttonPROMO.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonPROMO.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonPROMO.setCheckable(True)
        self.intbuttonPROMO.setObjectName(_fromUtf8("intbuttonPROMO"))
        self.horizontalLayout_2.addWidget(self.intbuttonPROMO)
        self.intbuttonPRISMA = QtGui.QPushButton(self.Internettab)
        self.intbuttonPRISMA.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonPRISMA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonPRISMA.setCheckable(True)
        self.intbuttonPRISMA.setObjectName(_fromUtf8("intbuttonPRISMA"))
        self.horizontalLayout_2.addWidget(self.intbuttonPRISMA)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_9 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_9.setAcceptDrops(True)
        self.pushButton_9.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/user-trash.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_9.setAutoRepeat(False)
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(1)
        self.horizontalLayout_17.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.intbuttonEUROKOS = QtGui.QPushButton(self.Internettab)
        self.intbuttonEUROKOS.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonEUROKOS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonEUROKOS.setCheckable(True)
        self.intbuttonEUROKOS.setObjectName(_fromUtf8("intbuttonEUROKOS"))
        self.horizontalLayout_17.addWidget(self.intbuttonEUROKOS)
        self.intbuttonDrogas = QtGui.QPushButton(self.Internettab)
        self.intbuttonDrogas.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonDrogas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonDrogas.setCheckable(True)
        self.intbuttonDrogas.setObjectName(_fromUtf8("intbuttonDrogas"))
        self.horizontalLayout_17.addWidget(self.intbuttonDrogas)
        self.intbuttonERMITAZAS = QtGui.QPushButton(self.Internettab)
        self.intbuttonERMITAZAS.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonERMITAZAS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonERMITAZAS.setCheckable(True)
        self.intbuttonERMITAZAS.setObjectName(_fromUtf8("intbuttonERMITAZAS"))
        self.horizontalLayout_17.addWidget(self.intbuttonERMITAZAS)
        self.intbuttonSenukai = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intbuttonSenukai.sizePolicy().hasHeightForWidth())
        self.intbuttonSenukai.setSizePolicy(sizePolicy)
        self.intbuttonSenukai.setMinimumSize(QtCore.QSize(0, 0))
        self.intbuttonSenukai.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonSenukai.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonSenukai.setCheckable(True)
        self.intbuttonSenukai.setObjectName(_fromUtf8("intbuttonSenukai"))
        self.horizontalLayout_17.addWidget(self.intbuttonSenukai)
        self.intbuttonMoki_Vezi = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intbuttonMoki_Vezi.sizePolicy().hasHeightForWidth())
        self.intbuttonMoki_Vezi.setSizePolicy(sizePolicy)
        self.intbuttonMoki_Vezi.setMinimumSize(QtCore.QSize(0, 0))
        self.intbuttonMoki_Vezi.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonMoki_Vezi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonMoki_Vezi.setCheckable(True)
        self.intbuttonMoki_Vezi.setObjectName(_fromUtf8("intbuttonMoki_Vezi"))
        self.horizontalLayout_17.addWidget(self.intbuttonMoki_Vezi)
        self.intbuttonJysk = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intbuttonJysk.sizePolicy().hasHeightForWidth())
        self.intbuttonJysk.setSizePolicy(sizePolicy)
        self.intbuttonJysk.setMinimumSize(QtCore.QSize(0, 0))
        self.intbuttonJysk.setMaximumSize(QtCore.QSize(16777215, 23))
        self.intbuttonJysk.setFocusPolicy(QtCore.Qt.NoFocus)
        self.intbuttonJysk.setCheckable(True)
        self.intbuttonJysk.setObjectName(_fromUtf8("intbuttonJysk"))
        self.horizontalLayout_17.addWidget(self.intbuttonJysk)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setContentsMargins(-1, 1, -1, 2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_5 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_5.setMouseTracking(False)
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-previous.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setShortcut(_fromUtf8(""))
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_4.setMouseTracking(False)
        self.pushButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_4.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-next.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/process-stop.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/view-refresh.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon8)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_22 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_22.setMouseTracking(False)
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-home.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_22.setIcon(icon9)
        self.pushButton_22.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_22.setFlat(True)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.horizontalLayout_4.addWidget(self.pushButton_22)
        self.lineEdit = QtGui.QLineEdit(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(360, 27))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_2 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 27))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(userdir + userprogpath + SEP("icons/go-jump.png"))), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_2.setIcon(icon10)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem4 = QtGui.QSpacerItem(40, 27, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.comboBox = QtGui.QComboBox(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboBox.setAcceptDrops(True)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(20)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.pushButton_12 = QtGui.QPushButton(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 23))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.progressBar_2 = QtGui.QProgressBar(self.Internettab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_2.sizePolicy().hasHeightForWidth())
        self.progressBar_2.setSizePolicy(sizePolicy)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 18))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.horizontalLayout_4.addWidget(self.progressBar_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line_3 = QtGui.QFrame(self.Internettab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.webView = QtWebKit.QWebView(self.Internettab)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.webView.setFont(font)
        self.webView.setMouseTracking(False)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_3.addWidget(self.webView)
        self.tabWidget.addTab(self.Internettab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_11.addWidget(self.line_4)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkboxmaxima = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxmaxima.sizePolicy().hasHeightForWidth())
        self.checkboxmaxima.setSizePolicy(sizePolicy)
        self.checkboxmaxima.setMinimumSize(QtCore.QSize(0, 0))
        self.checkboxmaxima.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxmaxima.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkboxmaxima.setAutoFillBackground(False)
        self.checkboxmaxima.setChecked(False)
        self.checkboxmaxima.setTristate(False)
        self.checkboxmaxima.setObjectName(_fromUtf8("checkboxmaxima"))
        self.verticalLayout_7.addWidget(self.checkboxmaxima)
        self.checkBoxnorfa = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxnorfa.sizePolicy().hasHeightForWidth())
        self.checkBoxnorfa.setSizePolicy(sizePolicy)
        self.checkBoxnorfa.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxnorfa.setChecked(False)
        self.checkBoxnorfa.setObjectName(_fromUtf8("checkBoxnorfa"))
        self.verticalLayout_7.addWidget(self.checkBoxnorfa)
        self.checkBoxiki = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxiki.sizePolicy().hasHeightForWidth())
        self.checkBoxiki.setSizePolicy(sizePolicy)
        self.checkBoxiki.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxiki.setChecked(False)
        self.checkBoxiki.setObjectName(_fromUtf8("checkBoxiki"))
        self.verticalLayout_7.addWidget(self.checkBoxiki)
        self.checkBoxrimi = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxrimi.sizePolicy().hasHeightForWidth())
        self.checkBoxrimi.setSizePolicy(sizePolicy)
        self.checkBoxrimi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBoxrimi.setChecked(False)
        self.checkBoxrimi.setObjectName(_fromUtf8("checkBoxrimi"))
        self.verticalLayout_7.addWidget(self.checkBoxrimi)
        self.checkboxAibe = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxAibe.sizePolicy().hasHeightForWidth())
        self.checkboxAibe.setSizePolicy(sizePolicy)
        self.checkboxAibe.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxAibe.setObjectName(_fromUtf8("checkboxAibe"))
        self.verticalLayout_7.addWidget(self.checkboxAibe)
        self.checkboxFRESH_MARKET = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxFRESH_MARKET.sizePolicy().hasHeightForWidth())
        self.checkboxFRESH_MARKET.setSizePolicy(sizePolicy)
        self.checkboxFRESH_MARKET.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxFRESH_MARKET.setObjectName(_fromUtf8("checkboxFRESH_MARKET"))
        self.verticalLayout_7.addWidget(self.checkboxFRESH_MARKET)
        self.checkboxPROMO = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxPROMO.sizePolicy().hasHeightForWidth())
        self.checkboxPROMO.setSizePolicy(sizePolicy)
        self.checkboxPROMO.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxPROMO.setObjectName(_fromUtf8("checkboxPROMO"))
        self.verticalLayout_7.addWidget(self.checkboxPROMO)
        self.checkboxPRISMA = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxPRISMA.sizePolicy().hasHeightForWidth())
        self.checkboxPRISMA.setSizePolicy(sizePolicy)
        self.checkboxPRISMA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxPRISMA.setObjectName(_fromUtf8("checkboxPRISMA"))
        self.verticalLayout_7.addWidget(self.checkboxPRISMA)
        self.checkboxEUROKOS = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxEUROKOS.sizePolicy().hasHeightForWidth())
        self.checkboxEUROKOS.setSizePolicy(sizePolicy)
        self.checkboxEUROKOS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxEUROKOS.setObjectName(_fromUtf8("checkboxEUROKOS"))
        self.verticalLayout_7.addWidget(self.checkboxEUROKOS)
        self.checkboxDrogas = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxDrogas.sizePolicy().hasHeightForWidth())
        self.checkboxDrogas.setSizePolicy(sizePolicy)
        self.checkboxDrogas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxDrogas.setObjectName(_fromUtf8("checkboxDrogas"))
        self.verticalLayout_7.addWidget(self.checkboxDrogas)
        self.checkboxERMITAZAS = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxERMITAZAS.sizePolicy().hasHeightForWidth())
        self.checkboxERMITAZAS.setSizePolicy(sizePolicy)
        self.checkboxERMITAZAS.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxERMITAZAS.setObjectName(_fromUtf8("checkboxERMITAZAS"))
        self.verticalLayout_7.addWidget(self.checkboxERMITAZAS)
        self.checkboxSenukai = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxSenukai.sizePolicy().hasHeightForWidth())
        self.checkboxSenukai.setSizePolicy(sizePolicy)
        self.checkboxSenukai.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxSenukai.setObjectName(_fromUtf8("checkboxSenukai"))
        self.verticalLayout_7.addWidget(self.checkboxSenukai)
        self.checkboxMoki_Vezi = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkboxMoki_Vezi.sizePolicy().hasHeightForWidth())
        self.checkboxMoki_Vezi.setSizePolicy(sizePolicy)
        self.checkboxMoki_Vezi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxMoki_Vezi.setObjectName(_fromUtf8("checkboxMoki_Vezi"))
        self.verticalLayout_7.addWidget(self.checkboxMoki_Vezi)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtondownloadpdf = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtondownloadpdf.sizePolicy().hasHeightForWidth())
        self.pushButtondownloadpdf.setSizePolicy(sizePolicy)
        self.pushButtondownloadpdf.setMinimumSize(QtCore.QSize(85, 0))
        self.pushButtondownloadpdf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtondownloadpdf.setObjectName(_fromUtf8("pushButtondownloadpdf"))
        self.horizontalLayout_8.addWidget(self.pushButtondownloadpdf)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_4 = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setBaseSize(QtCore.QSize(0, 0))
        self.checkBox_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_6.addWidget(self.checkBox_4)
        self.spinBox_3 = QtGui.QSpinBox(self.tab)
        self.spinBox_3.setMaximum(30)
        self.spinBox_3.setProperty("value", 7)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.horizontalLayout_6.addWidget(self.spinBox_3)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_3 = QtGui.QCheckBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.spinBox = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(365)
        self.spinBox.setSingleStep(5)
        self.spinBox.setProperty("value", 180)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.label_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.pushButton_8 = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_11.addWidget(self.line)
        self.verticalLayout.addLayout(self.verticalLayout_11)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_16.addWidget(self.label)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_2 = QtGui.QCheckBox(self.tab)
        self.checkBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.spinBox_2 = QtGui.QSpinBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(30)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.horizontalLayout_7.addWidget(self.spinBox_2)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_6 = QtGui.QFrame(self.tab)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plainTextEdit.setAcceptDrops(False)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plainTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setUndoRedoEnabled(True)
        self.plainTextEdit.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.progressBar = QtGui.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_13.addWidget(self.checkBox)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.spinBox_4 = QtGui.QSpinBox(self.tab_2)
        self.spinBox_4.setFrame(True)
        self.spinBox_4.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_4.setMinimum(100)
        self.spinBox_4.setMaximum(250)
        self.spinBox_4.setSingleStep(10)
        self.spinBox_4.setProperty("value", 150)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_9.addWidget(self.spinBox_4)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_2)
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_10.addWidget(self.pushButton_10)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pushButton_13 = QtGui.QPushButton(self.tab_2)
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_11.addWidget(self.pushButton_13)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem17)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_7.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Reklaminiai Parduotuvių Lankstinukai", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Maxima", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Norfa", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Iki", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Rimi", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Aibė", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "FRESH MARKET", None))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "PROMO CashCarry", None))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "PRISMA", None))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "EUROKOS", None))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "Drogas", None))
        self.comboBox_14.setItemText(0, _translate("MainWindow", "ERMITAŽAS", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Senukai", None))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Moki*Veži", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pdftab), _translate("MainWindow", "Lankstinukai", None))
        self.Intbuttonmaxima.setText(_translate("MainWindow", "Maxima", None))
        self.Intbuttonnorfa.setText(_translate("MainWindow", "Norfa", None))
        self.Intbuttoniki.setText(_translate("MainWindow", "Iki", None))
        self.Intbuttonrimi.setText(_translate("MainWindow", "Rimi", None))
        self.intbuttonaibe.setText(_translate("MainWindow", "Aibė", None))
        self.intbuttonFRESH_MARKET.setText(_translate("MainWindow", "FRESH MARKET", None))
        self.intbuttonPROMO.setText(_translate("MainWindow", "PROMO CashCarry", None))
        self.intbuttonPRISMA.setText(_translate("MainWindow", "PRISMA", None))
        self.intbuttonEUROKOS.setText(_translate("MainWindow", "EUROKOS", None))
        self.intbuttonDrogas.setText(_translate("MainWindow", "Drogas", None))
        self.intbuttonERMITAZAS.setText(_translate("MainWindow", "ERMITAŽAS", None))
        self.intbuttonSenukai.setText(_translate("MainWindow", "Senukai", None))
        self.intbuttonMoki_Vezi.setText(_translate("MainWindow", "Moki*Veži", None))
        self.intbuttonJysk.setText(_translate("MainWindow", "Jysk", None))
        self.pushButton_12.setText(_translate("MainWindow", "Į adresyną", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Internettab), _translate("MainWindow", "Internetas", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-weight:600;\">Lankstinukų atnaujinimas</span><br/></p></body></html>", None))
        self.checkboxmaxima.setText(_translate("MainWindow", "Maxima", None))
        self.checkBoxnorfa.setText(_translate("MainWindow", "Norfa", None))
        self.checkBoxiki.setText(_translate("MainWindow", "Iki", None))
        self.checkBoxrimi.setText(_translate("MainWindow", "Rimi", None))
        self.checkboxAibe.setText(_translate("MainWindow", "Aibė", None))
        self.checkboxFRESH_MARKET.setText(_translate("MainWindow", "FRESH MARKET", None))
        self.checkboxPROMO.setText(_translate("MainWindow", "PROMO CashCarry", None))
        self.checkboxPRISMA.setText(_translate("MainWindow", "PRISMA", None))
        self.checkboxEUROKOS.setText(_translate("MainWindow", "EUROKOS", None))
        self.checkboxDrogas.setText(_translate("MainWindow", "Drogas", None))
        self.checkboxERMITAZAS.setText(_translate("MainWindow", "ERMITAŽAS", None))
        self.checkboxSenukai.setText(_translate("MainWindow", "Senukai", None))
        self.checkboxMoki_Vezi.setText(_translate("MainWindow", "Moki*Veži", None))
        self.pushButtondownloadpdf.setText(_translate("MainWindow", "Tikrinti ir atsiųsti dabar", None))
        self.checkBox_4.setText(_translate("MainWindow", "Automatiškai tikrinti ar yra naujų lankstinukų kas  ", None))
        self.label_5.setText(_translate("MainWindow", "  dienų  ", None))
        self.checkBox_3.setText(_translate("MainWindow", "Automatiškai trinti senus lankstinukus po  ", None))
        self.label_2.setText(_translate("MainWindow", "  dienų    ", None))
        self.pushButton_8.setText(_translate("MainWindow", "Trinti dabar", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-weight:600;\">Programos atnaujinimas</span><br/></p></body></html>", None))
        self.checkBox_2.setText(_translate("MainWindow", "Automatiškai tikrinti įjungiant programą kas  ", None))
        self.label_4.setText(_translate("MainWindow", "  dienų  ", None))
        self.pushButton_7.setText(_translate("MainWindow", "Tikrinti ir atsiųsti dabar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Naujinimas", None))
        self.checkBox.setText(_translate("MainWindow", "Naudoti pdf.js. Lėtas ir kolkas kreivokai atvaizduoja su standartiniu webkit\'u.", None))
        self.label_6.setText(_translate("MainWindow", "PPI paveikslėlių kūrimui iš lankstinukų. 1920x*  ekranui reikėtų 200.", None))
        self.pushButton_10.setText(_translate("MainWindow", "Ištrinti paveikslėlius", None))
        self.label_7.setText(_translate("MainWindow", "Nespausk. Rimtai ;)", None))
        self.pushButton_13.setText(_translate("MainWindow", "Pagalba", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Nustatymai", None))
